version: '3.4'
volumes:
  sql_data: {}

services:
  fiap.pos.tech.challenge.api:
    image: ${DOCKER_REGISTRY-}fiappostechchallengeapi
    depends_on:
      - mongodb
    build:
      context: ../
      dockerfile: Src/Api/Dockerfile
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - sql_data:/data/db
