version: '3.4'

name: fiap-pos-techchallenge-micro-servico-pagamento-gurpo-71

volumes:
  sql_data: {}

services:
  FIAP.Pos.Tech.Challenge.Micro.Servico.Pagamento.api:
    image: fiappostechchallengemicroservicopagamentoapi:stand-alone
    depends_on:
      - mssqltools
    build:
      context: ../
      dockerfile: Src/Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8086
      - ASPNETCORE_HTTPS_PORTS=8087
    ports:
      - "8086:8086"
      - "8087:8087"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "SqlServer2019!"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-Usa", "-PSqlServer2019!", "-Q", "SELECT NAME FROM SYS.DATABASES"]
      interval: 10s
      retries: 20
    volumes:
      - sql_data:/var/opt/mssql
  mssqltools:
    image: mcr.microsoft.com/mssql-tools
    depends_on:
      - sqlserver
    volumes:
      - ../../FIAP-Pos-Tech-Challenge-Infra-Bd/Src/init-database.sh:/tmp/init-database.sh
      - ../../FIAP-Pos-Tech-Challenge-Infra-Bd/Src/tech-challenge-mer-1.sql:/tmp/tech-challenge-mer-1.sql
      - ../../FIAP-Pos-Tech-Challenge-Infra-Bd/Src/tech-challenge-mer-2.sql:/tmp/tech-challenge-mer-2.sql
    command: /bin/bash ./tmp/init-database.sh  
