version: '3.4'

name: fiap-pos-techchallenge-micro-servico-pagamento-gurpo-71

volumes:
  sql_data: {}

services:
  FIAP.Pos.Tech.Challenge.Micro.Servico.Pagamento.api:
    image: fiappostechchallengemicroservicopagamentoapi:stand-alone
    depends_on:
      - mongodb
    build:
      context: ../
      dockerfile: Src/Api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8086
      - ASPNETCORE_HTTPS_PORTS=8087
    ports:
      - "8086:8086"
      - "8087:8087"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - sql_data:/data/db
